changelog:
  exclude:
    labels:
      - backport
      - backport 1.0
      - backport 1.1
      - backport 1.2
      - backport 1.3
      - backport 2.0
      - backport 2.1
      - backport 2.2
      - backport 2.3
  categories:
    - title: New in OpenSearch 2.4
      labels:
        - v2.4.0
    - title: Other Changes
      labels:
        - "*"
